version: 2
jobs:
  build:
    working_directory: ~/zhcet
    docker:
      - image: circleci/openjdk:10-jdk-browsers
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Kolkata"

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Kolkata"

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew build

      - run:
          name: Run Tests
          command: ./gradlew bootJar

      - store_artifacts:
          path: build/libs
          destination: jar
      - store_test_results:
          path: build/reports/tests
