version: 2
jobs:
  build:
    working_directory: ~/zhcet
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Kolkata"

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Kolkata"

    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - save_cache:
          paths:
          - node_modules/
          key: npm-{{ checksum "package.json" }}

      - run:
          name: Download Gradle Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Build, Run Tests and Bundle JAR
          command: ./gradlew build

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Deploy to DockerHub
          command: bash .ci/scripts/docker-push.sh

      - store_artifacts:
          path: build/libs
          destination: jar
      - store_artifacts:
          path: build/reports/tests
          destination: tests
      - store_test_results:
          path: build/reports/tests
