version: 2
jobs:
  build:
    working_directory: ~/zhcet
    docker:
      - image: webpackcontrib/circleci-jdk9-node8
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Kolkata"

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Kolkata"

    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Install Yarn
          command: npm i -g yarn

      - run:
          name: Install JS Dependencies
          command: yarn

      - save_cache:
          paths:
          - node_modules/
          key: npm-{{ checksum "package.json" }}

      - run:
          name: Download Gradle Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Build JS
          command: yarn build

      - run:
          name: Build and Run Tests
          command: ./gradlew build

      - run:
          name: Bundle JAR
          command: ./gradlew bootJar

      - store_artifacts:
          path: build/libs
          destination: jar
      - store_artifacts:
          path: build/reports/tests
          destination: tests
      - store_test_results:
          path: build/reports/tests
